### ISSUE TITLE
`cargo install` installs v0.14.6 instead of v0.16.20 of ring package

### ISSUE THREAD

**Issue by ryuheechul** [evansmurithi/cloak#215]
Both files are pointing to `v0.16.20` as below.
https://github.com/evansmurithi/cloak/blob/23cdb2f6c10c06a9eab5ea2b3c0e69bbd21a780d/Cargo.toml#L17
https://github.com/evansmurithi/cloak/blob/23cdb2f6c10c06a9eab5ea2b3c0e69bbd21a780d/Cargo.lock#L517-L518

And that's how `cargo run` works as well
```
  Compiling ring v0.16.20
```

but with `cargo install`, it works differently
```
  Compiling ring v0.14.6
```

I don't know the why though as I'm not very familiar with how crates dependancy resolving works.

but v0.14.6 is also found at https://crates.io/crates/cloak/0.2.0/dependencies as well.

A couple of questions:

- is it intentional? if it is, why?
- is there a way to make `cargo install` to respect `Cargo.toml` and `Cargo.lock`?

### Why this is a problem (to me)?

I use Apple Silicon MacBook according to https://github.com/briansmith/ring/issues/1163#issuecomment-750405885, prior to 0.16.19 it fails to build and that's also what I experience when I try `cargo install cloak`

```
error: failed to run custom build command for `ring v0.14.6`
```

**Comment by evansmurithi** [comment]
@ryuheechul unfortunately the release 0.2.0 is outdated and haven't tagged a release since then. You can install using cargo from git using the following command:

```sh
cargo install cloak --git https://github.com/evansmurithi/cloak --branch master
```

I'll work on adding a proper release cycle for the project

**Comment by ryuheechul** [comment]
Thanks a lot and this worked well for me!

> ```shell
> cargo install cloak --git https://github.com/evansmurithi/cloak --branch master
> ```
